# Generated by Django

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('spreadsheet', 'Spreadsheet'), ('presentation', 'Presentation'), ('other', 'Other')], max_length=20)),
                ('minio_object_name', models.CharField(max_length=500)),
                ('minio_url', models.URLField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('file_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='chats.message')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='chats.chatsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['session', 'user'], name='uploads_upl_session_idx'),
                    models.Index(fields=['message'], name='uploads_upl_message_idx'),
                    models.Index(fields=['file_hash'], name='uploads_upl_file_ha_idx'),
                ],
            },
        ),
    ]
