# Generated by Django 5.2.7 on 2025-10-14 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='uploadedfile',
            new_name='uploads_upl_session_fbb549_idx',
            old_name='uploads_upl_session_idx',
        ),
        migrations.RenameIndex(
            model_name='uploadedfile',
            new_name='uploads_upl_message_e21338_idx',
            old_name='uploads_upl_message_idx',
        ),
        migrations.RenameIndex(
            model_name='uploadedfile',
            new_name='uploads_upl_file_ha_535f2e_idx',
            old_name='uploads_upl_file_ha_idx',
        ),
    ]
